spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshopping
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secretKey:200418304280pakaya200418304280pakaya
